# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1228beeb3000f32df868c4a271c993a0355fa653e1051059ed1d3fb881d6b43b8f6f595dd54c4b4924ade8df717760d9edf724fc86d381773d1b56a1f3551b

test:
  secret_key_base: 897c153dc4bbf87f4aff357095e62312fe944456cba83adf72f612a17a59112f18409d656d741fb3d313dc88ce2b70e314d1ed8d817bbf51e10cb1db0b118bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
